var mobiles = [{
		name: "Apple iPhone 6s, 32GB, 2GB RAM, 4G LTE, Silver",
		photo: "6s.JPG",
		price: 6888,
		brand: "Apple",
		model_name: "6s",
		display_type: "IPS",
		display_size: "4.7 Inches",
		display_resolution: "750×1334",
		touch_screen: "Yes",
		processor_chipset: "Yes",
		processor_cpu: "Dual-core",
		internal_memory: "32 GB",
		ram: "2 GB",
		memory_card_slot: "Not Available",
		os: "IOS",
		os_version: "iOS 9",
		rear_camera: "12 MP",
		fornt_camera: "5 MP",
		video_recording: "2160p@30fps",
		network_type: "2G, 3G, 4G",
		sim_type: "Nano SIM",
		color: "Silver",
		wifi: "Yes",
		bluetooth: "Yes",
		infrared: "No",
		radio: "No",
		nfc: "No",
		battery_capacity: 1715,
		weight: 143
	}, {
		name: "Apple iPhone 7 ,32 GB,2 GB RAM,4 G LTE,Black",
		photo: "7.jpg",
		price: 12199,
		brand: "Apple",
		model_name: "iPhone 7",
		display_type: "IPS",
		display_size: "4.7 Inches",
		display_resolution: "750× 1334",
		touch_screen: "Yes",
		processor_chipset: "Apple A10 Fusion",
		processor_cpu: "Quad - core",
		internal_memory: "32 GB",
		ram: "2 GB",
		memory_card_slot: "Not Available",
		os: "iOS",
		os_version: " iOS 10.0 .1",
		rear_camera: "12 MP",
		fornt_camera: "7 MP",
		video_recording: "2160 p @30fps",
		network_type: "2G , 3G , 4G",
		sim_type: "Nano SIM",
		color: "Black",
		wifi: "Yes",
		bluetooth: "Yes",
		infrared: "No",
		radio: "No",
		nfc: "Yes",
		battery_capacity: 1960,
		weight: 138
}, {
		name: " Apple iPhone Xs Max ,64 GB,4 GB RAM,4 G LTE,Space Grey",
		photo: "Xs_Max.JPG",
		price: 27000,
		brand: " Apple",
		model_name: " Xs Max ",
		display_type: "Super Retina HD",
		display_size: " 6.5 Inches",
		display_resolution: " 1242× 2688",
		touch_screen: " Yes",
		processor_chipset: " Apple A12 Bionic",
		processor_cpu: " Hexa - core",
		internal_memory: " 64 GB",
		ram: " 4 GB",
		memory_card_slot: " Not Available",
		os: " IOS",
		os_version: " IOS 12",
		rear_camera: " 12 MP + 12 MP",
		fornt_camera: " 7 MP",
		video_recording: " 2160 p @60fps",
		network_type: " 2G , 3G , 4G",
		sim_type: " Nano SIM",
		color: " Grey",
		wifi: " Yes",
		bluetooth: " Yes",
		infrared: " No",
		radio: " No",
		nfc: " Yes",
		battery_capacity: " 3174",
		weight: " 208 "
}, {
		name: "Huawei Mate 9, 64GB, 4GB RAM. 4G LTE, Black",
		photo: "Mate9.JPG",
		price: 5999,
		brand: "	Huawei",
		model_name: "Mate 9",
		display_type: "IPS",
		display_size: "5.9 Inches",
		display_resolution: "1080 x 1920 pixels",
		touch_screen: "Yes",
		processor_chipset: "Hisilicon Kirin 960",
		processor_cpu: "Octa-core",
		internal_memory: "	64 GB",
		ram: "4 GB",
		memory_card_slot: "microSD, up to 256 GB",
		os: "Android",
		os_version: "Android OS, v7.0 (Nougat)",
		rear_camera: "20 MP + 12 MP",
		fornt_camera: "8 MP",
		video_recording: "2160p@30fps, 1080p@30/60fps",
		network_type: " 2G, 3G , 4G",
		sim_type: "Nano SIM",
		color: "Black",
		wifi: "Yes",
		bluetooth: "Yes",
		infrared: "Yes",
		radio: "No",
		nfc: "Yes",
		battery_capacity: "4000",
		weight: "190g"
}, {
		name: "Huawei P10 Lite Dual SIM,32 GB,4 GB RAM,4 G LTE,Black",
		photo: "P10.JPG",
		price: 5739,
		brand: " Huawei",
		model_name: " P10 Lite ",
		display_type: "IPS",
		display_size: " 5.2 Inches",
		display_resolution: " 1080 x 1920",
		touch_screen: " Yes",
		processor_chipset: " HiSilicon Kirin 658",
		processor_cpu: " Octa - core",
		internal_memory: " 32 GB",
		ram: " 4 GB",
		memory_card_slot: " microSD,up to 256 GB",
		os: " Android",
		os_version: " Android 7.0(Nougat)",
		rear_camera: " 12 MP",
		fornt_camera: " 8 MP",
		video_recording: " 1080 p @60fps",
		network_type: " 2G , 3G , 4G",
		sim_type: " Nano SIM",
		color: " Black",
		wifi: " Yes",
		bluetooth: " Yes",
		infrared: " No",
		radio: " Yes",
		nfc: " No",
		battery_capacity: " 3000",
		weight: " 146 g "
}, {
		name: "Huawei P30 Lite Dual SIM,128 GB,4 GB RAM,4 G LTE,Black",
		photo: "P30.JPG",
		price: " 5000",
		brand: " Huawei",
		model_name: " P30 Lite ",
		display_type: "IPS ",
		display_size: " 6.15 Inches",
		display_resolution: " 1080× 2312",
		touch_screen: " Yes",
		processor_chipset: " Hisilicon Kirin 710",
		processor_cpu: " Octa - core",
		internal_memory: " 128 GB",
		ram: " 4 GB",
		memory_card_slot: " microSD,up to 512 GB ",
		os: " Android",
		os_version: " Android 9.0(Pie);EMUI 9",
		rear_camera: " 24 MP + 8 MP + 2 MP",
		fornt_camera: " 32 MP",
		video_recording: " 1080 p @30fps",
		network_type: " 2G , 3G , 4G ",
		sim_type: " Nano SIM",
		color: " Black",
		wifi: " Yes",
		bluetooth: " Yes",
		infrared: " No",
		radio: " No",
		nfc: " No",
		battery_capacity: " 3340",
		weight: 159
}, {
		name: " Huawei Y7 Prime 2019 Dual SIM,32 GB ,3 GB RAM ,4 G LTE ,Red ",
		photo: "Y7.JPG",
		price: 2999,
		brand: " Huawei",
		model_name: " Y7 Prime 2019 ",
		display_type: "IPS ",
		display_size: " 6.26 Inches",
		display_resolution: " 720× 1520",
		touch_screen: " Yes",
		processor_chipset: " Qualcomm SDM450 Snapdragon 450",
		processor_cpu: " Octa - core",
		internal_memory: " 32 GB",
		ram: " 3 GB",
		memory_card_slot: " microSD,up to 512 GB ",
		os: " Android",
		os_version: " Android 8.1(Oreo)",
		rear_camera: " 13 MP + 2 MP",
		fornt_camera: " 16 MP",
		video_recording: " 1080 p @30fps",
		network_type: " 2G , 3G , 4G ",
		sim_type: " Nano SIM",
		color: " Red",
		wifi: " Yes",
		bluetooth: " Yes",
		infrared: " No",
		radio: " Yes",
		nfc: " No",
		battery_capacity: " 4000",
		weight: 168
}, {
		name: " Huawei Y5 Lite Dual SIM,16 GB ,1 GB RAM ,4 G LTE ,Black ",
		photo: " Y5.JPG",
		price: 1630,
		brand: " Huawei",
		model_name: " Y5 Lite ",
		display_type: "LCD ",
		display_size: " 5.45 Inches",
		display_resolution: " 720× 1440",
		touch_screen: " Yes",
		processor_chipset: " MediaTek MT6739",
		processor_cpu: " Quad - core",
		internal_memory: " 16 GB",
		ram: " 1 GB",
		memory_card_slot: " microSD,up to 128 GB ",
		os: " Android",
		os_version: " Android 8.1(Oreo)",
		rear_camera: " 8 MP",
		fornt_camera: " 5 MP",
		video_recording: " 1080 p @30fps",
		network_type: " 2G , 3G , 4G ",
		sim_type: " Nano SIM",
		color: " Black",
		wifi: " Yes",
		bluetooth: " Yes",
		infrared: " No",
		radio: " Yes",
		nfc: " No",
		battery_capacity: " 3020",
		weight: 145
}, {
		name: "Samsung Galaxy S10 Dual SIM, 128GB, 8GB RAM, 4G LTE, Prism White",
		photo: "S10.JPG",
		price: 16499,
		brand: "Samsung",
		model_name: "Galaxy S10",
		display_type: "Dynamic AMOLED",
		display_size: "6.1 Inches",
		display_resolution: "1440×3040",
		touch_screen: "Yes",
		processor_chipset: "Exynos 9820 Octa",
		processor_cpu: "Octa-core",
		internal_memory: "128 GB",
		ram: "	8 GB",
		memory_card_slot: "microSD, up to 512 GB",
		os: "Android",
		os_version: "Android 9.0 (Pie) One UI",
		rear_camera: "12 MP + 12 MP + 16 MP",
		fornt_camera: "10 MP",
		video_recording: "2160p@60fps",
		network_type: "2G, 3G , 4G",
		sim_type: "	Nano SIM",
		color: "	White",
		wifi: "	Yes",
		bluetooth: "	Yes",
		infrared: "No",
		radio: "No",
		nfc: "	Yes",
		battery_capacity: "3400",
		weight: 157
}, {
		name: "Samsung Galaxy Note9, Dual SIM, 512GB, 6GB RAM, 4G LTE, Blue",
		photo: "Note9.JPG",
		price: 19999,
		brand: "Samsung",
		model_name: "Galaxy Note9",
		display_type: "Super AMOLED",
		display_size: "	6.4 Inches",
		display_resolution: "1440 x 2960",
		touch_screen: "Yes",
		processor_chipset: "Exynos 9810 Octa",
		processor_cpu: "Octa-core",
		internal_memory: "512 GB",
		ram: "6 GB",
		memory_card_slot: "microSD, up to 512 GB",
		os: "Android",
		os_version: "Android 8.1 (Oreo)",
		rear_camera: "12 MP + 12 MP",
		fornt_camera: "	8 MP",
		video_recording: "2160p@60fps",
		network_type: "	2G, 3G, 4G",
		sim_type: "	Micro SIM",
		color: "Blue",
		wifi: "Yes",
		bluetooth: "Yes",
		infrared: "No",
		radio: "No",
		nfc: "Yes",
		battery_capacity: "	4000",
		weight: 201
}, {
		name: "Samsung Galaxy A9 2018 Dual SIM, 128GB, 6GB RAM, 4G LTE, Blue",
		photo: "A9.JPG",
		price: 7499,
		brand: "Samsung",
		model_name: "Galaxy A9 2018",
		display_type: "Super AMOLED",
		display_size: "6.3 Inches",
		display_resolution: "1080×2220",
		touch_screen: "Yes",
		processor_chipset: "Qualcomm SDM660 Snapdragon 660",
		processor_cpu: "Octa-core",
		internal_memory: "128 GB",
		ram: "6 GB",
		memory_card_slot: "microSD, up to 512 GB",
		os: "Android",
		os_version: "Android 8.0 (Oreo)",
		rear_camera: "24 MP + 5 MP + 10 MP + 8 MP",
		fornt_camera: "24 MP",
		video_recording: "2160p@30fps",
		network_type: "2G, 3G, 4G",
		sim_type: "Nano SIM",
		color: "Blue",
		wifi: "Yes",
		bluetooth: "Yes",
		infrared: "No",
		radio: "Yes",
		nfc: "Yes",
		battery_capacity: "	3800",
		weight: 183
}, {
		name: "Samsung Galaxy A70 Dual SIM, 128GB, 6GB RAM, 4G LTE, Coral",
		photo: "A70.JPG",
		price: 7000,
		brand: "Samsung",
		model_name: "Galaxy A70",
		display_type: "Super AMOLED",
		display_size: "	6.7 Inches",
		display_resolution: "1080×2400",
		touch_screen: "Yes",
		processor_chipset: "Qualcomm SDM675 Snapdragon 675",
		processor_cpu: "Octa-core",
		internal_memory: "128 GB",
		ram: "	6 GB",
		memory_card_slot: "microSD, up to 512 GB",
		os: "Android",
		os_version: "Android 9.0 (Pie); One UI",
		rear_camera: "Android 9.0 (Pie); One UI",
		fornt_camera: "32 MP",
		video_recording: "2160p@30fps",
		network_type: "2G, 3G, 4G",
		sim_type: "Nano SIM",
		color: "Orange",
		wifi: "Yes",
		bluetooth: "Yes",
		infrared: "No",
		radio: "Yes",
		nfc: "Yes",
		battery_capacity: "4500",
		weight: 183
}, {
		name: "Samsung Galaxy Note 5 Dual Sim, 32GB, 4GB RAM, 4G LTE - Black",
		photo: "Note5.JPG",
		price: 6999,
		brand: "Samsung",
		model_name: "N920DS-Black",
		display_type: "Super AMOLED",
		display_size: "5.7 Inches",
		display_resolution: "1440 × 2560 pixels",
		touch_screen: "Yes",
		processor_chipset: "Exynos 7420",
		processor_cpu: "Quad-core",
		internal_memory: "32 GB",
		ram: "4 GB",
		memory_card_slot: "Not Available",
		os: "Android",
		os_version: "Android 5.1.1 (Lollipop)",
		rear_camera: "16 MP",
		fornt_camera: "5 MP",
		video_recording: "2160p@30fps, 1080p@60fps, optical stabilization",
		network_type: "2G, 3G, 4G",
		sim_type: "Nano SIM",
		color: "Nano SIM",
		wifi: "Yes",
		bluetooth: "Yes",
		infrared: "No",
		radio: "No",
		nfc: "Yes",
		battery_capacity: "3000",
		weight: 171
}, {
		name: "Samsung Galaxy A50 Dual SIM, 128GB, 4GB RAM, 4G LTE, Black",
		photo: "A50.JPG",
		price: 5599,
		brand: "Samsung",
		model_name: "Galaxy A50",
		display_type: "Super AMOLED",
		display_size: "6.4 Inches",
		display_resolution: "1080×2340",
		touch_screen: "Yes",
		processor_chipset: "Exynos 9610 Octa",
		processor_cpu: "Octa-core",
		internal_memory: "128 GB",
		ram: "4 GB",
		memory_card_slot: "microSD, up to 512 GB",
		os: "Android",
		os_version: "Android 9.0 (Pie)",
		rear_camera: "25 MP + 5 MP + 8 MP",
		fornt_camera: "25 MP",
		video_recording: "1080p@30fps",
		network_type: "2G, 3G, 4G",
		sim_type: "Nano SIM",
		color: "Black",
		wifi: "Yes",
		bluetooth: "Yes",
		infrared: "No",
		radio: "Yes",
		nfc: "Yes",
		battery_capacity: "4000",
		weight: 166
}
];
var labtops = [
	{
		name: "Dell Inspiron 13 7370 Laptop – Core i7 1.8GHz 8GB 256GB Shared Win10 13.3inch FHD Silver",
		photo: "7370.JPG",
		price: 21199,
		brand: "Dell",
		color: "Silver",
		os: "Windows 10",
		screen_size: "13.3 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "IPS",
		Processor: "Intel Core i7 1.8 GHz 8550U 8th Generation",
		ram: "8 GB DDR4",
		storage: "256 GB SSD",
		graphics: "Intel HD Graphics",
		battery: "38WHr",
		no_of_cells: 3
	}, {
		name: "Dell G3 17 3779 Gaming Laptop – Corei7 2.2GHz 16GB 2TB+256GB 6GB DOS 17.3inch FHD Black",
		photo: "3779.JPG",
		price: 28000,
		brand: "Dell",
		color: "Black",
		os: "DOS",
		screen_size: "17.3 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "IPS Anti-Glare LED Backlit Display",
		Processor: "Intel Core i7 2.2 GHz 8750H 8th Generation",
		ram: "16 GB DDR4",
		storage: "	2 TB HDD + 256 GB SSD",
		graphics: "	NVIDIA GeForce GTX 1060 6 GB",
		battery: "40WHr",
		no_of_cells: 3
	}, {
		name: "Dell Inspiron 14 5482 Convertible Touch Laptop – Corei5 1.6GHz 8GB 1TB 2GB Win10 14inch FHD Silver",
		photo: "5482.JPG",
		price: 16999,
		brand: "Dell",
		color: "Silver",
		os: "Windows 10",
		screen_size: "	14 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "IPS LED-Backlit Touch Display",
		Processor: "Intel Core i5 1.6 GHz 8250U 8th Generation",
		ram: "8 GB DDR4",
		storage: "1 TB	HDD",
		graphics: "NVIDIA GeForce MX130 2 GB",
		battery: "42 WHr",
		no_of_cells: 3
	}, {
		name: "Dell Inspiron 15 5577 Gaming Laptop – Core i7 2.8GHz 16GB 1TB+128GB 4GB Win10 15.6inch FHD Black",
		photo: "5577.jpg",
		price: 21499,
		brand: "Dell",
		color: "Black",
		os: "windows 10",
		screen_size: "15.6 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "Anti-Glare LED-Backlit Display",
		Processor: "Intel Core i7 2.8 GHz 7700HQ 7th Generation",
		ram: "16 GB DDR4",
		storage: "	1 TB HDD + 128 GB SSD",
		graphics: "NVIDIA GeForce GTX 1050 4 GB",
		battery: "	74 WHr",
		no_of_cells: 6
	}, {
		name: "HP Pavilion 15-CS1001NE Laptop – Core i7 1.8GHz 16GB 1TB+128GB 4GB Win10 15.6inch FHD Mineral Silver",
		photo: "cs1001.JPG",
		price: 21499,
		brand: "HP",
		color: "Silver",
		os: "Windows 10",
		screen_size: "15.6 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "IPS anti-glare micro-edge WLED-backlit",
		Processor: "Intel Core i7 1.8 GHz 8565U 8th Generation",
		ram: "16 GB DDR4",
		storage: "1 TB HDD + 128 GB SSD",
		graphics: "NVIDIA GeForce MX150 4 GB",
		battery: "41WHr",
		no_of_cells: 3
	}, {
		name: "HP Pavilion 15-CX0012NE Gaming Laptop – Core i5 2.3GHz 16GB 1TB 4GB Win10 15.6inch FHD Black",
		photo: "cs1001.JPG",
		price: 20499,
		brand: "HP",
		color: "Black",
		os: "Windows 10",
		screen_size: "15.6 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "IPS anti-glare micro-edge WLED-backlit",
		Processor: "	Intel Core i5 2.3 GHz 8300H 8th Generation",
		ram: "16 GB DDR4",
		storage: "1 TB HDD",
		graphics: "NVIDIA GeForce GTX 1050 4 GB",
		battery: "52.5 WHr",
		no_of_cells: 3
	}, {
		name: "HP OMEN 15-DC0014NE Gaming Laptop – Core i7 2.2GHz 16GB 1TB+256GB 6GB Win10 15.6inch FHD Shadow Black",
		photo: "dc0014.JPG",
		price: 32998,
		brand: "HP",
		color: "Black",
		os: "Windows 10",
		screen_size: "15.6 Inches",
		resolution: "UHD (3840 x 2160)",
		technology: "IPS anti-glare micro-edge WLED-backlit",
		Processor: "Intel Core i7 2.2 GHz 8750H 8th Generation",
		ram: "16 GB DDR4",
		storage: "	1 TB HDD+ 256 GB SSD",
		graphics: "NVIDIA GeForce GTX 1050 Ti 4 GB",
		battery: "70 WHr",
		no_of_cells: 4
	}, {
		name: "HP Pavilion Power 15-CB009NE Laptop – Core i7 2.8GHz 16GB 1TB+128GB 4GB Win10 15.6inch FHD Black",
		photo: "cb009.JPG",
		price: 21899,
		brand: "HP",
		color: "Black",
		os: "Windows 10",
		screen_size: "15.6 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "IPS anti-glare WLED-backlit",
		Processor: "Intel Core i7 2.8 GHz 7700HQ 7th Generation",
		ram: "	16 GB DDR4",
		storage: "1 TB HDD + 128 GB SSD",
		graphics: "NVIDIA GeForce GTX 1050 4 GB",
		battery: "70 WHr",
		no_of_cells: 4
	}, {
		name: "Lenovo Yoga C930 Convertible Touch Laptop – Core i7 1.8GHz 16GB 512GB Shared Win10 13.9inch FHD Iron Grey",
		photo: "C930.JPG",
		price: 31999,
		brand: "Lenovo",
		color: "Grey",
		os: "Windows10",
		screen_size: "13.9 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "IPS",
		Processor: "Intel Core i7 1.8 GHz 8550U 8th Generation",
		ram: "16 GB DDR4",
		storage: "512 GB SSD",
		graphics: "Intel UHD Graphics 620",
		battery: "	60 WHr",
		no_of_cells: 4
	}, {
		name: "Lenovo Legion Y530 Gaming Laptop – Core i7 2.2GHz 16GB 1TB+256GB 6GB DOS 15.6inch FHD Black",
		photo: "Y530.JPG",
		price: 26999,
		brand: "Lenovo",
		color: "Black",
		os: "DOS",
		screen_size: "15.6 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "IPS",
		Processor: "Intel Core i7 2.2 GHz 8750H 8th Generation",
		ram: "16 GB DDR4",
		storage: "1 TB HDD+ 256 GB SSD",
		graphics: "	NVIDIA GeForce GTX 1060 6 GB",
		battery: "52.2WHr",
		no_of_cells: 4
	}, {
		name: "Lenovo ThinkPad T480 Laptop – Core i7 1.8GHz 8GB 1TB 2GB Win10Pro 14inch FHD Black",
		photo: "T480.JPG",
		price: 30999,
		brand: "Lenovo",
		color: "Black",
		os: "Windows 10 Pro",
		screen_size: "14 Inches",
		resolution: "FHD (1920 x 1080)",
		technology: "	IPS",
		Processor: "Intel Core i7 1.8 GHz 8550U 8th Generation",
		ram: "8 GB DDR4",
		storage: "	1 TB HDD",
		graphics: "NVIDIA GeForce MX150 2 GB",
		battery: "50WHr",
		no_of_cells: 4
	}
];
var ac = [{
	name: "Fresh SMART PLASMA Split Air Conditioner, Cooling Only - 1.5 HP",
	photo: "1.5hP.JPG",
	price: 7950,
	brand: "Fresh",
	type: "Split Air Conditioner",
	Horse_Power: "1.5 HP",
	Cooling_System: "Cooling Only",
	Coverage_Area: "Up To 12 Square Meter",
	Heating_Function: "No",
	Anti_Corrosion_Outdoor_Unit: "Yes",
	Turbo_Function: "Yes",
	Dry_Function: "Yes"
}, {
	name: "Fresh SMART PLASMA Split Air Conditioner ,Cooling Only - 2.5 HP",
	photo: "2.5hP.JPG",
	price: 10600,
	brand: "Fresh",
	Type: "Split Air Conditioner",
	Horse_Power: "2.5 HP",
	Cooling_System: "Cooling Only",
	Coverage_Area: "Up To 20 Square Meter",
	Heating_Function: "No",
	Anti_Corrosion_Outdoor_Unit: "Yes",
	Turbo_Function: "Yes",
	Dry_Function: "Yes"
}, {
	name: "Samsung Split Air Conditioner, Cooling Heating, 2.25 HP - AR18JPFTPWQNBT",
	photo: "1.5HPs.JPG",
	price: 11649,
	brand: "Samsung",
	Type: "Split Air Conditioner",
	Horse_Power: "2.25 HP",
	Cooling_System: "Cooling & Heating",
	Coverage_Area: "	Up To 18 Square Meter",
	Cooling_Capacity: "18000 BTU",
	Heating_Function: "Yes",
	Anti_Corrosion_Outdoor_Unit: "Yes",
	Turbo_Function: "Yes",
	Dry_Function: "Yes"
}, {
	name: "Samsung Split Air Conditioner, Cooling & Heating, 1.5 HP - AR12JPFTPWQNBT",
	photo: "1.5HPs.JPG",
	price: 8999,
	brand: "Samsung",
	Type: "Split Air Conditioner",
	Horse_Power: "1.5 HP",
	Cooling_System: "Cooling & Heating",
	Coverage_Area: "Up To 12 Square Meter",
	Cooling_Capacity: "12000 BTU",
	Heating_Function: "Yes",
	Anti_Corrosion_Outdoor_Unit: "Yes",
	Turbo_Function: "Yes",
	Dry_Function: "Yes"
}, {
	name: "Sharp Split Digital With Plasmacluster, Cooling & Heating, 2.25 HP - AY-AP18UHE",
	photo: "2.25hpsh.JPG",
	price: 11660,
	brand: "Sharp",
	Type: "Split Air Conditioner",
	Horse_Power: "2.25 HP",
	Cooling_System: "	Cooling & Heating",
	Coverage_Area: "Up To 18 Square Meter",
	Cooling_Capacity: "17400",
	Heating_Function: "Yes",
	Anti_Corrosion_Outdoor_Unit: "	Yes",
	Turbo_Function: "Yes",
	Dry_Function: "Yes"
}, {
	name: "Sharp Split Digital With Plasmacluster, Cooling & Heating, 1.5 HP - AY-AP12UHEA",
	photo: "1.5hpsh.JPG",
	price: 9349,
	brand: "Sharp",
	Type: "Split Air Conditioner",
	Horse_Power: "1.5 HP",
	Cooling_System: "Cooling & Heating",
	Coverage_Area: "Up To 12 Square Meter",
	Cooling_Capacity: "12000",
	Heating_Function: "Yes",
	Anti_Corrosion_Outdoor_Unit: "Yes",
	Turbo_Function: "Yes",
	Dry_Function: "Yes"
}, {
	name: "York Split Air Conditioner, Cooling & Heating, 5 HP - YHGE36XE-HC-RX-IN",
	photo: "5 HP.JPG",
	price: 22500,
	brand: "York",
	Type: "Split Air Conditioner",
	Horse_Power: "5 HP",
	Cooling_System: "Cooling & Heating",
	Coverage_Area: "Up To 40 Square Meter",
	Cooling_Capacity: "37585",
	Heating_Function: "Yes",
	Anti_Corrosion_Outdoor_Unit: "Yes",
	Turbo_Function: "Yes",
	Dry_Function: "Yes"
}, {
	name: "York Split Air Conditioner, Cooling Only, 1.5 HP - YKHFXC012BBM4-FX-IN",
	photo: "1.5 HPy.JPG",
	price: 7999,
	brand: "York",
	Type: "Split Air Conditioner",
	Horse_Power: "1.5 HP",
	Cooling_System: "Cooling Only",
	Coverage_Area: "Up To 12 Square Meter",
	Cooling_Capacity: "12454",
	Heating_Function: "No",
	Anti_Corrosion_Outdoor_Unit: "Yes",
	Turbo_Function: "Yes",
	Dry_Function: "Yes"
}];
var tv = [{
	name: "LG 32 Inch Smart TV Full HD LED TV - 32LJ570U",
	photo: "32.JPG",
	price: 3899,
	brand: "LG",
	Screen_Size: "32 inch",
	Screen_Technology: "LED",
	HD_Type: "Full HD",
	Screen_Resolution: "1366 * 768",
	Curved_Design: "No",
	_4K_Technology: "No",
	Built_In_Receiver: "Yes",
	Smart_Connection: "Yes",
	Wi_Fi_Connection: "Yes",
	Number_Of_HDMI_Inputs: "2",
	Number_Of_USB_Ports: "No"
}, {
	name: "LG 43 Inch Full HD LED TV With Built-In Receiver - 43LK5100",
	photo: "43.JPG",
	price: 5999,
	brand: "LG",
	Screen_Size: "43 inch",
	Screen_Technology: "LED",
	HD_Type: "Full HD",
	Screen_Resolution: "1920 × 1080",
	Curved_Design: "No",
	_4K_Technology: "No",
	Built_In_Receiver: "Yes",
	Smart_Connection: "No",
	Wi_Fi_Connection: "No",
	Number_Of_HDMI_Inputs: "2",
	Number_Of_USB_Ports: "1"
}, {
	name: "Samsung 32 Inch HD LED TV With Built_In_Receiver - UA32N5000-RS",
	photo: "32s.JPG",
	price: 3499,
	brand: "Samsung",
	Screen_Size: "32 inch",
	Screen_Technology: "LED",
	HD_Type: "HD",
	Screen_Resolution: "1364×720",
	Curved_Design: "No",
	_4K_Technology: "No",
	Built_In_Receiver: "Yes",
	Smart_Connection: "No",
	Wi_Fi_Connection: "No",
	Number_Of_HDMI_Inputs: "2",
	Number_Of_USB_Ports: "1"
}, {
	name: "Samsung 55 Inch 4K Ultra HD Smart LED TV With Built_In_Receiver - UA55RU7100",
	photo: "55.JPG",
	price: 9999,
	brand: "Samsung",
	Screen_Size: "55 inch",
	Screen_Technology: "LED",
	HD_Type: "Ultra HD",
	Screen_Resolution: "3840×2160",
	Curved_Design: "No",
	_4K_Technology: "Yes",
	Built_In_Receiver: "Yes",
	Smart_Connection: "Yes",
	Wi_Fi_Connection: "Yes",
	Number_Of_HDMI_Inputs: "3",
	Number_Of_USB_Ports: "2"
}, {
	name: "TORNADO 32 Inch HD LED TV - 32EL8250E",
	photo: "32t.JPG",
	price: 2599,
	brand: "TORNADO",
	Screen_Size: "32 inch",
	Screen_Technology: "LED",
	HD_Type: "HD",
	Screen_Resolution: "1366×768",
	Curved_Design: "No",
	_4K_Technology: "No",
	Built_In_Receiver: "No",
	Smart_Connection: "No",
	Wi_Fi_Connection: "No",
	Number_Of_HDMI_Inputs: "2",
	Number_Of_USB_Ports: "1"
}, {
	name: "Tornado 43 Inch Smart Full HD Smart LED TV - 43EB7110E",
	photo: "43.JPG",
	price: 5349,
	brand: "TORNADO",
	Screen_Size: "43 inch",
	Screen_Technology: "LED",
	HD_Type: "Full HD",
	Screen_Resolution: "1920×1080",
	Curved_Design: "No",
	_4K_Technology: "No",
	Built_In_Receiver: "No",
	Smart_Connection: "Yes",
	Wi_Fi_Connection: "Yes",
	Number_Of_HDMI_Inputs: "3",
	Number_Of_USB_Ports: "2"
}, {
	name: "Toshiba 32 Inch HD LED TV - 32L2700EA",
	photo: "32tos.JPG",
	price: 3199,
	brand: "Toshiba",
	Screen_Size: "32 inch",
	Screen_Technology: "LED",
	HD_Type: "HD",
	Screen_Resolution: "1366×768",
	Curved_Design: "No",
	_4K_Technology: "No",
	Built_In_Receiver: "No",
	Smart_Connection: "No",
	Wi_Fi_Connection: "No",
	Number_Of_HDMI_Inputs: "3",
	Number_Of_USB_Ports: "2"
}, {
	name: "Toshiba 55 Inch Full HD LED TV- 55L270MEA",
	photo: "55.JPG",
	price: 8299,
	brand: "Toshiba",
	Screen_Size: "55 inch",
	Screen_Technology: "LED",
	HD_Type: "Full HD",
	Screen_Resolution: "1080 x 1920 FHD",
	Curved_Design: "No",
	_4K_Technology: "No",
	Built_In_Receiver: "No",
	Smart_Connection: "No",
	Wi_Fi_Connection: "No",
	Number_Of_HDMI_Inputs: "3",
	Number_Of_USB_Ports: "2"
}];


	let help = window.location + "";
	let kind = help.substring(help.lastIndexOf('?') + 1, help.lastIndexOf('='));
function load_product() {
	
	let name = (help.substr(help.indexOf('=') + 1)).replace(/%20/gi, ' ');
	let a = name.substr(name.indexOf(' ') + 1);
	let b = name.substring(0, name.indexOf(' ') + 1)

	let carry = [];
	if (kind == "mob") carry = mobiles;
	else if (kind == "lab") carry = labtops;
	else if (kind == "tv") carry = tv;
	else carry = ac;

	let pos = carry.findIndex(function (element) {
		return element.name.includes(b) && element.name.includes(a);
	});
	document.getElementById("path").innerHTML = "<a href='index.html' style='color:#333'>Home</a> / <a href='products.html?" + kind + "' style='color:#333'>" + kind + "</a> / " + carry[pos].brand + " / " + name;
	load_page(carry[pos],name);

}

function load_page(carry,name) {
	//load photo
	document.getElementById("productImage").src = "images/" + carry.photo;
	//load name ,load price
	document.getElementById("sub-details").innerHTML = "<h2 style='margin: 10% 20px;font-weight: 400;'>" + carry.name + "</h2><h2 style='margin: 8% 20px;font-weight: 400;'>Price : " + carry.price + " EGP</h2><a class='bu' onclick='add(\""+name+"\",\""+kind+"\")' style='width:20%;margin: 10% 20px;padding:15px 10px 5px;'>ADD TO CART</a>";
	//make a table of it
	let temp = '';
	for (let i in carry) {
		if(i=='photo')continue;
		temp += '<tr><td>' + i + '</td><td>' + carry[i] + '</td></tr>';
	}
	document.getElementById("table").innerHTML = temp;

}

let ex = '';

function add(name, kind) {
	String.prototype.splice = function (idx, rem, str) {
		return this.slice(0, idx) + str + this.slice(idx + Math.abs(rem));
	};
	pos = ex.indexOf(kind);
	if (pos == -1) ex += kind + "{" + name + "}";
	else if (ex.indexOf(name) == -1) {
		ex = ex.splice(pos + kind.length + 1, 0, name + ",");
	}
	adjust();
}
function adjust(){
	document.getElementById("tocart").href = "add%20to%20cart.html?" + ex;
	let ak=document.getElementsByClassName("ak");
	for(let i in ak){
		ak[i].href="products.html?"+i+ex;
	}
}